#!/bin/bash

#     This file is part of O4erednik.
#
#     O4erednik is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License or
#     (at your option) any later version.
#
#     O4erednik is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with O4erednik.  If not, see <http://www.gnu.org/licenses/>.
#
#     Copyright 2014 Fomichev Dmitriy


PID=$$
# L=$(uname -n)
if ! [ -z $1 ]; then files="\"ifile\": \"$1\""; else exit 1; fi
if ! [ -z $2 ]; then files="$files, \"ofile\": \"$2\""; fi
n=0
for i in $(sed -n 's/^\%chk=\(.*\)$/\1/gp' $1)
do
    files="$files, \"chkfile$n\": \"$i\""
    n=$(($n+1))
done
echo -e "[\"A\", [\"g03\", $PID, {$files }, {}]]" >/dev/udp/127.0.0.1/50000
exec sleep 10s








