#!/bin/bash
PID=$$
L=$(uname -n)
if [ -z $* ]; then exit 1; fi
exec 5<>/dev/tcp/$L/9043
echo -e "a::$PID::$*" >&5 
answer=$(cat <&5)
exec 5<&-
exec 5>&-
if [[ $answer == "OK" ]];
then
    while true; do sleep 1s; done
else
    echo "Can't connect to the daemon"
    exit 1
fi







