# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './settings.ui'
#
# Created: Fri Dec 27 17:25:54 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName(_fromUtf8("SettingsDialog"))
        SettingsDialog.resize(589, 336)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        self.tabWidget = QtGui.QTabWidget(SettingsDialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 571, 271))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Network = QtGui.QWidget()
        self.Network.setEnabled(True)
        self.Network.setObjectName(_fromUtf8("Network"))
        self.groupBox = QtGui.QGroupBox(self.Network)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 541, 91))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 211, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.host = QtGui.QLineEdit(self.groupBox)
        self.host.setEnabled(True)
        self.host.setGeometry(QtCore.QRect(10, 40, 231, 21))
        self.host.setInputMask(_fromUtf8(""))
        self.host.setText(_fromUtf8(""))
        self.host.setObjectName(_fromUtf8("host"))
        self.rhost = QtGui.QLineEdit(self.groupBox)
        self.rhost.setGeometry(QtCore.QRect(300, 40, 221, 21))
        self.rhost.setInputMask(_fromUtf8(""))
        self.rhost.setObjectName(_fromUtf8("rhost"))
        self.autohost = QtGui.QCheckBox(self.groupBox)
        self.autohost.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.autohost.setTristate(False)
        self.autohost.setObjectName(_fromUtf8("autohost"))
        self.groupBox_2 = QtGui.QGroupBox(self.Network)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 541, 131))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(300, 30, 61, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.bcast = QtGui.QLineEdit(self.groupBox_2)
        self.bcast.setGeometry(QtCore.QRect(10, 50, 231, 21))
        self.bcast.setInputMask(_fromUtf8(""))
        self.bcast.setObjectName(_fromUtf8("bcast"))
        self.lbcast = QtGui.QLineEdit(self.groupBox_2)
        self.lbcast.setGeometry(QtCore.QRect(302, 50, 221, 21))
        self.lbcast.setInputMask(_fromUtf8(""))
        self.lbcast.setObjectName(_fromUtf8("lbcast"))
        self.lbcastsame = QtGui.QCheckBox(self.groupBox_2)
        self.lbcastsame.setGeometry(QtCore.QRect(300, 70, 211, 21))
        self.lbcastsame.setObjectName(_fromUtf8("lbcastsame"))
        self.tabWidget.addTab(self.Network, _fromUtf8(""))
        self.Environment = QtGui.QWidget()
        self.Environment.setObjectName(_fromUtf8("Environment"))
        self.groupBox_3 = QtGui.QGroupBox(self.Environment)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 551, 101))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gcom = QtGui.QLineEdit(self.groupBox_3)
        self.gcom.setGeometry(QtCore.QRect(130, 20, 371, 21))
        self.gcom.setObjectName(_fromUtf8("gcom"))
        self.gcomch = QtGui.QToolButton(self.groupBox_3)
        self.gcomch.setGeometry(QtCore.QRect(510, 20, 30, 22))
        self.gcomch.setObjectName(_fromUtf8("gcomch"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gtmp = QtGui.QLineEdit(self.groupBox_3)
        self.gtmp.setGeometry(QtCore.QRect(130, 50, 371, 21))
        self.gtmp.setObjectName(_fromUtf8("gtmp"))
        self.gtmpch = QtGui.QToolButton(self.groupBox_3)
        self.gtmpch.setGeometry(QtCore.QRect(510, 50, 30, 22))
        self.gtmpch.setObjectName(_fromUtf8("gtmpch"))
        self.groupBox_4 = QtGui.QGroupBox(self.Environment)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 120, 551, 51))
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.viscom = QtGui.QLineEdit(self.groupBox_4)
        self.viscom.setGeometry(QtCore.QRect(130, 20, 371, 21))
        self.viscom.setObjectName(_fromUtf8("viscom"))
        self.viscomch = QtGui.QToolButton(self.groupBox_4)
        self.viscomch.setGeometry(QtCore.QRect(510, 20, 30, 22))
        self.viscomch.setObjectName(_fromUtf8("viscomch"))
        self.groupBox_5 = QtGui.QGroupBox(self.Environment)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 551, 61))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.textcom = QtGui.QLineEdit(self.groupBox_5)
        self.textcom.setGeometry(QtCore.QRect(130, 20, 371, 21))
        self.textcom.setObjectName(_fromUtf8("textcom"))
        self.textcomch = QtGui.QToolButton(self.groupBox_5)
        self.textcomch.setGeometry(QtCore.QRect(510, 20, 30, 22))
        self.textcomch.setObjectName(_fromUtf8("textcomch"))
        self.tabWidget.addTab(self.Environment, _fromUtf8(""))
        self.Behaviour = QtGui.QWidget()
        self.Behaviour.setObjectName(_fromUtf8("Behaviour"))
        self.groupBox_6 = QtGui.QGroupBox(self.Behaviour)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 541, 80))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.servermode = QtGui.QCheckBox(self.groupBox_6)
        self.servermode.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.servermode.setObjectName(_fromUtf8("servermode"))
        self.clientmode = QtGui.QCheckBox(self.groupBox_6)
        self.clientmode.setGeometry(QtCore.QRect(280, 30, 141, 21))
        self.clientmode.setObjectName(_fromUtf8("clientmode"))
        self.tabWidget.addTab(self.Behaviour, _fromUtf8(""))
        self.Save = QtGui.QPushButton(SettingsDialog)
        self.Save.setGeometry(QtCore.QRect(240, 300, 91, 22))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Cancel = QtGui.QPushButton(SettingsDialog)
        self.Cancel.setGeometry(QtCore.QRect(480, 300, 91, 22))
        self.Cancel.setObjectName(_fromUtf8("Cancel"))
        self.Default = QtGui.QPushButton(SettingsDialog)
        self.Default.setGeometry(QtCore.QRect(360, 300, 101, 22))
        self.Default.setObjectName(_fromUtf8("Default"))

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.Cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Настройки", None))
        self.groupBox.setTitle(_translate("SettingsDialog", "Адрес компьютера", None))
        self.label.setText(_translate("SettingsDialog", "Локальный:", None))
        self.label_2.setText(_translate("SettingsDialog", "Удаленный:", None))
        self.autohost.setText(_translate("SettingsDialog", "Автоматически", None))
        self.groupBox_2.setTitle(_translate("SettingsDialog", "Широковещательный адрес", None))
        self.label_3.setText(_translate("SettingsDialog", "Прием:", None))
        self.label_4.setText(_translate("SettingsDialog", "Отправка:", None))
        self.lbcastsame.setText(_translate("SettingsDialog", "Такой же как и для отправки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Network), _translate("SettingsDialog", "Сеть", None))
        self.groupBox_3.setTitle(_translate("SettingsDialog", "Gaussian", None))
        self.label_5.setText(_translate("SettingsDialog", "Команда:", None))
        self.gcomch.setText(_translate("SettingsDialog", "...", None))
        self.label_8.setText(_translate("SettingsDialog", "Временная папка:", None))
        self.gtmpch.setText(_translate("SettingsDialog", "...", None))
        self.groupBox_4.setTitle(_translate("SettingsDialog", "Визуализатор", None))
        self.label_6.setText(_translate("SettingsDialog", "Команда:", None))
        self.viscomch.setText(_translate("SettingsDialog", "...", None))
        self.groupBox_5.setTitle(_translate("SettingsDialog", "Текстовый редактор", None))
        self.label_7.setText(_translate("SettingsDialog", "Команда:", None))
        self.textcomch.setText(_translate("SettingsDialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Environment), _translate("SettingsDialog", "Окружение", None))
        self.groupBox_6.setTitle(_translate("SettingsDialog", "Удаленная отправка задач (требуется перезапуск):", None))
        self.servermode.setText(_translate("SettingsDialog", "Режим сервера", None))
        self.clientmode.setText(_translate("SettingsDialog", "Режим клиента", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Behaviour), _translate("SettingsDialog", "Поведение", None))
        self.Save.setText(_translate("SettingsDialog", "Сохранить", None))
        self.Cancel.setText(_translate("SettingsDialog", "Отмена", None))
        self.Default.setText(_translate("SettingsDialog", "По умолчанию", None))

